version: "3.7"
services:

  koa:
    image: brusw/blog-koa:latest
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    volumes:
      - /srv/www/blog/config:/usr/src/app/config
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 100M
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      placement:
        constraints: [node.role==worker]

  nuxt:
    image: brusw/blog-nuxt:latest
    ports:
      - "5000:5000"
    networks:
      - frontend
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200M
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      placement:
        constraints: [node.role==worker]

  admin:
    image: brusw/blog-admin:latest
    ports:
      - "8080:8080"
    networks:
      - frontend
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 50M
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      placement:
        constraints: [node.role==worker]

networks:
  frontend:
    external: true
  backend:
    external: true
